services:
  frontend:
    container_name: sota6si_frontend
    hostname: sota6si_frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - api
    networks:
      - frontend

networks:
  frontend:
